server.port=8092

spring.datasource.url=jdbc:postgresql://localhost:5433/pointservice
spring.datasource.username=sneha
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

debug=true

logging.level.org.springframework=DEBUG

userservice.host=host.docker.internal:8099
userservice.path=/user/validation