server.port=8092

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pointservice}
spring.datasource.username=${DB_USERNAME:sneha}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

debug=true

logging.level.org.springframework=DEBUG

userservice.host=${USER_SERVICE_HOST:userservice.userservicenamespace}
userservice.path=/user/validation